### ISSUE TITLE
Predictable Environment Variable Indicates block number can be manipulated?

### ISSUE THREAD

**Issue by xanderdunn** [ConsenSys/mythril#1553]
## Description

[Here](https://github.com/ConsenSys/mythril/blob/2518cc8b656bb0d21a80058c3f7f1def13da8db7/mythril/analysis/module/modules/dependence_on_predictable_vars.py#L96) the `Dependence on predictable environment variable` check writes that `block number and timestamp are predictable and can be manipulated by a malicious miner.` 

I might be misreading this, but block number can't actually be manipulated by a miner, correct? It's certainly predictable. It's always just +1, right? But it shouldn't be manipulatable.  My smart contract has a speed bump that relies on block numbers being monotonically increasing to prevent flash loan usage.

**Comment by norhh** [comment]
Hi.  @xanderdunn, it's a warning of low severity, since it's possible for a miner to rent a lot of hardware and ignore your transactions for a few blocks to get the block number the miner needs if the contract is dependent on block number as a source of randomness. In your case, it shouldn't be an issue.

**Comment by xanderdunn** [comment]
That makes sense, thank you!
