### ISSUE TITLE
Implement multi-transactional analysis

### ISSUE THREAD

**Issue by suhabe** [ConsenSys/mythril#191]
Mythril reports an assertion violation on this benchmark:
```
pragma solidity ^0.4.19;

contract Benchmark {
    uint256 private param;

    function Benchmark(uint256 _param) public {
        require(_param > 0);
        param = _param;
    }

    function run() {
        assert(param > 0);
    }
}
```

child of #203

**Comment by b-mueller** [comment]
This is a great example for why we need multi-transactional analysis. To make this work we need to:

- Implement the CREATE opcode and allow deployments in LASER using the contract creation bytecode instead of runtime bytecode; The contract creation bytecode sets the initial world state (`private=0`)
- Simulate a series of transactions (t1 and t2) starting from the initial state;
- In the contract above, there is only one non-exceptional end state for t1. As the world change is unchanged the is no need to simulate a second one. The assert is not reported;
- If we added a function `setParamTo1` that changes `param` to 1, there would be two valid end states: One where the world state remains unchanged, and one where `param` is changed to 1. With multi-transactional analysis, Mythril would now simulate t2 with `param=1` as the initial state. The assert would be reported including the 2 transactions triggering it.
- If we added a function `setParam` that changes `param` to `calldata_4`, there would be one end state where `param` assumes a symbolic value. Mythril would solve for `calldata_4>0` in t2 and again report the assert violation.

**Comment by JoranHonig** [comment]
I don't think we need multi-transactional analysis for the contract reported by suhabe. 

The thing we want to discover is whether it is possible to write 0 to param. So we basically want to discover invariants, and to do that we shouldn't need multiple transaction runs. We would, however, need to model the constructor.

How this situation could be solved:
Execute the constructior and constrain storage using that analysis. From that we would get the constraint param > 0.
Symbolically execute the program to find any writes to param, and use their constraints to determine invariance of param. (Not necessary in this case)
In the assertion check use invariants/constraints discovered to see reachability of revert state

**Comment by b-mueller** [comment]
True, it's not needed for that particular example, even though in a sense we'd be executing two transactions (one running the constructor, followed by the transaction executing the runtime bytecode).

I think in more complex cases, "finding any writes to param" in a reliable way will become challenging, because there might be cases where multiple intermediate steps are necessary for the write to become possible. Maybe something like this:


```
contract Wut {
    uint256 private param;

    function Wut() public {
        param = 0;
    }
    function inc() {
        param += 1;
    }
    function run() {
        assert(param > 3);
    }
}
```

**Comment by b-mueller** [comment]
And the counter example. This should not report an issue:

```
contract Wut {
    uint256 private param;

    function Wut() public {
        param = 0;
    }

    function inc() {
        if (param < 3) {
            param += 1;
        }
    }

    function run() {
        assert(param > 3);
    }
}
```

**Comment by JoranHonig** [comment]
In determining the invariants you would need to consider the path constraints of the write. 
The thing we would try to achieve with multi-transactional analysis is actually determining these invariants. I'm not sure that executing multiple transactions is the most efficient way to do this.

**Comment by b-mueller** [comment]
Perhaps a good way of approaching this is to come up with a series of increasingly complex problems? For example, I wonder what happens if you factor in writes to symbolic storage addresses (like in the dynamically sized arrays case).

**Comment by JoranHonig** [comment]
Take the first Wut contract. To be sure of an overflow, using multi-transactional analysis, we would need to do a ton of executions.

**Comment by JoranHonig** [comment]
@suhabe Using multi-transactional analysis how would we find an overflow where only one is added each exec.

Example function (lets assume a gets initialized to 0):
```
  function doX() public returns (bool) {
    a++;
    return true;
  }
```
