### ISSUE TITLE
Report does not give proper function names

### ISSUE THREAD

**Issue by joshuata** [ConsenSys/mythril#208]
All report tests are failing on MacOS due to issues retrieving function names.

This is the current master on MacOS

Expected:
```json
"issues": [
  {
    "title": "Integer Underflow",
    "description": "A possible integer underflow exists in the function `sendeth(address,uint256)`.\nThe subtraction may result in a value < 0.",
    "function": "sendeth(address,uint256)",
    "type": "Warning",
    "address": 649,
    "debug": "<DEBUG-DATA>"
  }]
```

Current:
```json
"issues": [
  {
    "title": "Integer Underflow",
    "description": "A possible integer underflow exists in the function `_function_0xa3210e87`.\nThe subtraction may result in a value < 0.",
    "function": "_function_0xa3210e87",
    "type": "Warning",
    "address": 649,
    "debug": "<DEBUG-DATA>"
  }]
```

**Comment by joshuata** [comment]
Update:

This is a completely different problem than I initially thought. I can replicate this problem by running the program on any of the test cases once. However, as soon as I run it a second time, the problem is resolved.

Example:
```
$ ./myth -x tests/testdata/input_contracts/calls.sol -o markdown
```
```
# Analysis results for tests/testdata/input_contracts/ether_send.sol

## Ether send

- Type: Warning
- Contract: Crowdfunding
- Function name: `_function_0x6c343ffe`
- PC address: 722
```

```
$ ./myth -x tests/testdata/input_contracts/calls.sol -o markdown
```
```
# Analysis results for tests/testdata/input_contracts/ether_send.sol

## Ether send

- Type: Warning
- Contract: Crowdfunding
- Function name: `withdrawfunds()`
- PC address: 722
...
```

**Comment by b-mueller** [comment]
This is caused by the way Mythril resolves function names.

There's a `signatures.json` file in the user's home directory that contains mappings of known function hashes to function names. If the function hash is not in the file, Mythril uses the generic `_function_0x...` identifiers. 

Every time you analyze a Solidity file, the hashes from that file are added to `signatures.json`.

What makes things more complicated is that there's a [default signatures file](https://github.com/ConsenSys/mythril/blob/master/signatures.json), but I think this is currently not installed automatically. So if you install Mythril you start with an empty one.

Also, in your example, I would actually expect it to work the first time (the function names should be available after the compilation step).

**Comment by b-mueller** [comment]
Would be easy to add. But I still wonder why you're not getting the function names in the first analysis pass.
