### ISSUE TITLE
Faulty Report Generation (Duplicates?)

### ISSUE THREAD

**Issue by simondlr** [ConsenSys/mythril#298]
**Describe the bug**
Mythril is generating what seems to be a faulty report, generating duplicates in the code. You can see the faulty report here: keeps pointing to setTokenURI and keeps pointing to the whole code as the issue vs specific sections.

https://github.com/UjoTeam/contracts-badges/blob/fix/audit/patronage_mythril.md

**To Reproduce**
Fork: https://github.com/UjoTeam/contracts-badges/tree/fix/audit
Run: myth -xo markdown contracts/UjoPatronageBadges.sol > patronage_mythril.md

**Expected behavior**
Report doesn't include duplicates and links to code that starts at the beginning of the 

**Desktop (please complete the following information):**
 - OS: OS X
 - Version: Sierra

**Comment by JoranHonig** [comment]
HI @simondlr, thanks a lot for the report. I believe the different issues aren't actually duplicate issues (bc they have different program counter values).

We actually run analysis on the evm bytecode vs solidity, to map an instruction to a piece of code we use solc. If the whole piece of code is shown, that means that solc mapped that instruction to the entire code. I think your problem (multiple seemingly duplicate issues) is probably caused by false positives (i.e. mythril observes some weird behavior, assumes it is wrong and reports it, while it is actually intended by the compiler). These false positives can be situated in the code used for function handling etc, which could indeed be mapped to the entire piece of code by solidity.

Ofc we'll need to find the actual cause of the false positive, before we can be sure that this is the problem. Thanks for providing the contract, that will make it a lot easier!

**Comment by simondlr** [comment]
Thanks. If I understand you correctly, I don't think it's necessarily a false positive, because I know there are parts of the code that will overflow (the mint function). But the mint() function isn't shown in the report.

I don't know how Mythril works, but feels like it is finding something but correctly showing the issues an just "re-uses" the previous template. Something like that (if that makes sense). :)

**Comment by p0n1** [comment]
@simondlr @JoranHonig  I notice that `Function name: setTokenURI(uint256,string)` appears multiple times in patronage_mythril.md report.

```js
pragma solidity ^0.4.21;

contract MappingString {

    mapping(uint256 => string) internal tokenURIs;

    function setTokenURI(uint256 _tokenID, string URI) public {
        tokenURIs[_tokenID] = URI;
    }
}
```

If you try the simplest code above, your will get same result (5 times).

It should be related with string loops in ERC721 contract code. Mythril is lack of good loop handling by now, So the mythril analysis process for `UjoPatronageBadges.sol` is mostly about function `getTotalMintedPerCombination(string,address,uint256)` and `setTokenURI(uint256,string)`,

**Comment by simondlr** [comment]
I don't quite understand this.

So the loop handling is causing it to run out of depth and then quit? As a result, it's not finding the other issues/errors, like the overflow in the mint() function?

**Comment by p0n1** [comment]
@simondlr I didn't read mint() function closely.

Do you mean this `totalMintedBadgesPerCombination[_cid][_beneficiary][_usdCost] += 1;` could lead to overflow?

But I tried to comment out `setTokenURI()` and `getTotalMintedPerCombination()` function and Mythril returned [more results](https://gist.github.com/p0n1/372800036496656415df2655d9e84ce4).

Still nothing valuable because `totalMintedBadgesPerCombination` could contain string loops too.

**Comment by simondlr** [comment]
Thanks for the more results.

Yes. mint() function has the multiplication and addition that could lead to overflow, but it is not being returned in the report?

**Comment by JoranHonig** [comment]
@p0n1 How mythril handles loops should not hinder mythril in entering all the public functions, this might be another problem (but I'd need to look at the generated traces a bit more). In any case, the worklist implementation is almost done, so we'll have a better way of working with loops/state explosion 

tbh; to be sure wat the problem is I think some debugging is required.

**Comment by simondlr** [comment]
Anything I can help with?

**Comment by JoranHonig** [comment]
@simondlr possibly 😄 . If you hop by on our gitter channel https://gitter.im/ConsenSys/mythril, we can probably have have an easier time discussing things 👍
