### ISSUE TITLE
Handle interface contracts gracefully

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/mythril#46]
I have this unimplemented interface contract, in the same folder as a contract that inherits it. 

```
pragma solidity ^0.4.18;
contract Interface{    
    function transfer(address _to, uint _value, bytes _data) public returns (bool);
    event Transfer(address indexed _from, address indexed _to, uint256 indexed _value, bytes _data);
}
```
The dir structure is something like: 

```
contracts/
├── Interface.sol
├── Implemented.sol
├── SomethingElse.sol
```

So, I'd like to be able to run `myth -x contracts/*.sol`, but when I do, I get: 

```Traceback (most recent call last):
  File "/Users/primary/.pyenv/versions/3.6.1/bin/myth", line 205, in <module>
    name, bytecode = compile_solidity(solc_binary, file)
  File "/Users/primary/.pyenv/versions/3.6.1/lib/python3.6/site-packages/mythril/ether/util.py", line 36, in compile_solidity
    return [m.group(1), m.group(2)]
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by step21** [comment]
Is there a reason why it needs to be a separate file? If you would include it in the file or give only the actual contract as argument, it should work afaik.

**Comment by b-mueller** [comment]
> Handle interface contracts gracefully

I added a fix in [master](https://github.com/ConsenSys/mythril) so that library contracts are now treated as a bytecode-less contract. 

You have to be aware though that when scanning a directory like that, Mythril doesn't scan the contract files one-by-one. Instead it maps the contracts to addresses 0x0000(...), 0x1111(...) etc. in the order supplied (alphabetical in that case) and then starts the analysis with the first contract as the entry point. So scanning like that might not make sense.

I am currently looking into better solutions for using Mythril in a Truffle/Ganache context.

**Comment by maurelian** [comment]
> Is there a reason why it needs to be a separate file? If you would include it in the file or give only the actual contract as argument, it should work afaik.

Good question. I'm auditing other people's contract systems, and would prefer not to have to edit it. Also, IMO if it's valid to the compiler, it should be valid to the analyzer. :)

**Comment by step21** [comment]
@maurelian Of course, just curious when quickly looking at it. Thanks for clarifying.

**Comment by maurelian** [comment]
Fixed here: https://github.com/ConsenSys/mythril/commit/f1e07baa8fbfb1841b6d475f07f066756af80c21
