### ISSUE TITLE
Python 3.6

### ISSUE THREAD

**Issue by shashank-srikant** [ConsenSys/mythril#482]
Please clearly indicate that Python 3.6 is a requirement to run Mythril.
Running Python 3.5, as seen from #478, can cause very weird behavior.
I tried finding whether this dependence on Py3.6 has been mentioned anywhere in the current docs/wiki/etc., and didn't manage to spot it anywhere.
This will just save people a lot of time and energy.

Thanks.

**Comment by norhh** [comment]
except `3.5.2` i think the other versions don't have any issues because in one of the virtualenv i am using python `3.5.0`(also `3.5.5`) without any problem. That specific version had some weird issues, I am not even sure how it ran for you in the first place :smiley: . It might be a good idea to add this to the docs.Thanks a lot for the suggestion.

**Comment by shashank-srikant** [comment]
was a noted added to the readme/docs regarding 3.5.2 then?

**Comment by norhh** [comment]
Its added in the wiki.

**Comment by shashank-srikant** [comment]
awesome; thanks.
