### ISSUE TITLE
JUMPDEST instructions missing in CFG

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril#487]
## Description

1. Not sure if it's a bug or a feature, but the JUMPDEST at the start of jump targets isn't shown in the CFG. See e.g. the JUMPI to offset 159, and the target node starts at offset 160.

![cfg](https://user-images.githubusercontent.com/5194767/44848615-a8598d80-ac81-11e8-9e33-231b7510ec61.png)

2. Function names used to be shown in the CFG at the start of each function, those are gone as well.

## How to Reproduce

Using Mythril 0.18.11 Pypi:

```console
$ myth -g cfg.html -ia 0x35efabf6e2d970a3bc3fa1de991ec63987c127bc
```

## Expected behavior

Include the JUMPDEST instruction at the start of the node or the function name if it's the start of a function.

## Environment

- Mythril version: 0.18.11 Pypi
- Python version: 3.6.3
- OS and Version: Mac OS High Sierra

**Comment by dmuhs** [comment]
Tracing the bug a little further down, it doesn't seem to be related to the node's start address.

On a side note, the start address not being set and the `JUMPDEST` condition [in the callgraph module](https://github.com/ConsenSys/mythril/blob/master/mythril/analysis/callgraph.py#L100) never executing seems to be another issue.

Looking at the missing `JUMPDEST` instructions however, the disassembly works fine and the instruction lists stay consistent. Its preserved throughout the state initialisations when the LASER object is initialized. After `laser.sym_exec()` is called [here](https://github.com/ConsenSys/mythril/blob/master/mythril/analysis/symbolic.py#L38), the resulting nodes do not contain the `JUMPDEST` instructions anymore. So somewhere in the LASER routines the instruction is cut away. See the debugger screen below.

![screenshot from 2018-09-03 22-07-08](https://user-images.githubusercontent.com/5565837/45000520-d9112e00-afc5-11e8-9923-8d114ba3f2d7.png)

**Comment by JoranHonig** [comment]
Hey @dmuhs, so sorry for not responding earlier.

This happened semi intentional. If we have a jump or jumpi instruction then the mutator function changes the pc to the pc of the jumpdest, the @instruction decorator in postprocessing then increments the pc again, which will lead to the jumpdest not being executed/having a separate state. This is stll a correct execution, which is why I left it like that.

An easy dirty initial fix would be to change the pc to jumpdest -1, but that doesn't feel like the best solution

**Comment by dmuhs** [comment]
@JoranHonig Thanks for clarifying. After having spent just a couple of hours with the LASER core routines it's still quite a bit of black magic to me.
As for the pc index of the JUMPDEST, instead of manipulating the `@instruction` decorator and having to deal with all instructions, we could simply decrement the index in the `JUMP` and `JUMPI` mutator functions. In these functions there's already logic handling `JUMPDEST` instructions, so it wouldn't add any bloat to the functions and we could simply set the index, e.g. in `jumpi_` like such (in `instructions.py:842`):

```python
        if instr['opcode'] == "JUMPDEST":
            if (type(condi) == bool and condi) or (type(condi) == BoolRef and not is_false(condi)):
                new_state = copy(global_state)
                new_state.mstate.pc = index - 1
                new_state.mstate.depth += 1
                new_state.mstate.constraints.append(condi)

                states.append(new_state)
```

While that still doesn't look too clean as the -1 isn't self-explanatory, I think it's more elegant than handling the case in the instruction decorator. If we were to do the latter, we'd have to get the jump destination address there again and set the pc accordingly. But then we would've repeated the same logic again, which would make it harder to maintain and refactor.

Thoughts?

**Comment by JoranHonig** [comment]
What about something like the following:
```
@instruction(auto_increment==False)
def jumpi_(self, global_state):
    ...
    new_state.mstate.pc = index
    ...
```
I think this will be simpler, and more easy to directly understand the meaning

**Comment by dmuhs** [comment]
I agree that the decorator looks cleaner. For the jump mutator function, this approach works well. In the jumpi function we will have to manually increase the pc in the cases where the stack's operation (`op0`) cannot be parsed to an integer, and in the false case.

When giving the `@instruction` decorator arguments, we will end up with three nested functions. To keep things readable, I will convert it into a class-based decorator. I would also propose a name change as it only really touches the pc state - so something like `PCMutator` would fit (and avoid shadowing with the `Instruction` class if we stick to the class name convention).
