### ISSUE TITLE
Add command line option to configure number of transactions executed

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril#543]
## Description

As a user, I'd like to specify the "transaction depth", i.e. the number of transactions executed. For example:

```
$ myth --num-transactions 3 -x contract.sol
```

**Comment by JoranHonig** [comment]
Closing this because the laser can now detect by itself if it should execute more transactions. 
However we still want to set an upper limit, #572 is an issue that describes what needs to be implemented

This issue is therefore out of date. @b-mueller fun fact, the limit is now set at 3 so your example works for the current master!
