### ISSUE TITLE
Tests should just check for swc id

### ISSUE THREAD

**Issue by norhh** [ConsenSys/mythril#671]
## Description
Tests in CI should just check for swc-id

**Comment by JoranHonig** [comment]
This is in reference to: https://github.com/ConsenSys/mythril-classic/pull/669

The problem that seems to be that changes in the description of an issue make tests fail and its difficult to update the expected outputs. Limiting the tests to only check for the swc id would solve this problem. 
However, the report_tests cover a different aspects: 
- report generation (json, markdown, text). 
- vulnerability detection capabilities (they check if the same vulnerabilities will keep being detected)
- issue content correctness (for example, if an issue points to the correct function and instruction)
By limiting the current tests to only swc ids we'd lose the 1 and 3. 

I think this test should be replaced altogether with a test module that tests report generation in isolation (tests 1), and edelweiss which runs based of the swc registry (tests 2 and part of 3).
I don't think should never test if the issue content is correct (but we'll have to see how edelweiss turns out to what extent we'll have specific test cases for that).

**Comment by norhh** [comment]
Now this is redundant due to report tests being removed and swc's are tested elsewhere
